[package]
name = "demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subql-contracts = { git = "https://github.com/subquery/network-contracts", branch = "kepler-network" }
